name: Policy Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Running tests on Opa policy files and capability files
    - name: Run make test
      run: make test
