name: Policy Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Running tests on Opa policy files and capability files
    - name: Download opa
      run: sudo curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | grep browser_download_url | grep opa_linux_amd64 | cut -d '"' -f 4 | wget -qi - -P /opt/opa/bin/
    - name: Rename opa
      run: sudo mv /opt/opa/bin/opa_linux_amd64 /opt/opa/bin/opa
    - name: Run make test
      run: make test
